version: '3.8'

services:
  postgres:
    image: postgres
    container_name: find-my-igroup
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: find-my-igroup
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
